<?php

use Illuminate\Database\Seeder;

class KotasTableSeeder extends Seeder
{
  /**
  * Run the database seeds.
  *
  * @return void
  */
  public function run()
  {
    $Kota = [
      array('id' => '1101','provinsi_id' => '11','nama' => 'Kabupaten Simeulue'),
      array('id' => '1102','provinsi_id' => '11','nama' => 'Kabupaten Aceh Singkil'),
      array('id' => '1103','provinsi_id' => '11','nama' => 'Kabupaten Aceh Selatan'),
      array('id' => '1104','provinsi_id' => '11','nama' => 'Kabupaten Aceh Tenggara'),
      array('id' => '1105','provinsi_id' => '11','nama' => 'Kabupaten Aceh Timur'),
      array('id' => '1106','provinsi_id' => '11','nama' => 'Kabupaten Aceh Tengah'),
      array('id' => '1107','provinsi_id' => '11','nama' => 'Kabupaten Aceh Barat'),
      array('id' => '1108','provinsi_id' => '11','nama' => 'Kabupaten Aceh Besar'),
      array('id' => '1109','provinsi_id' => '11','nama' => 'Kabupaten Pidie'),
      array('id' => '1110','provinsi_id' => '11','nama' => 'Kabupaten Bireuen'),
      array('id' => '1111','provinsi_id' => '11','nama' => 'Kabupaten Aceh Utara'),
      array('id' => '1112','provinsi_id' => '11','nama' => 'Kabupaten Aceh Barat Daya'),
      array('id' => '1113','provinsi_id' => '11','nama' => 'Kabupaten Gayo Lues'),
      array('id' => '1114','provinsi_id' => '11','nama' => 'Kabupaten Aceh Tamiang'),
      array('id' => '1115','provinsi_id' => '11','nama' => 'Kabupaten Nagan Raya'),
      array('id' => '1116','provinsi_id' => '11','nama' => 'Kabupaten Aceh Jaya'),
      array('id' => '1117','provinsi_id' => '11','nama' => 'Kabupaten Bener Meriah'),
      array('id' => '1118','provinsi_id' => '11','nama' => 'Kabupaten Pidie Jaya'),
      array('id' => '1171','provinsi_id' => '11','nama' => 'Kota Banda Aceh'),
      array('id' => '1172','provinsi_id' => '11','nama' => 'Kota Sabang'),
      array('id' => '1173','provinsi_id' => '11','nama' => 'Kota Langsa'),
      array('id' => '1174','provinsi_id' => '11','nama' => 'Kota Lhokseumawe'),
      array('id' => '1175','provinsi_id' => '11','nama' => 'Kota Subulussalam'),
      array('id' => '1201','provinsi_id' => '12','nama' => 'Kabupaten Nias'),
      array('id' => '1202','provinsi_id' => '12','nama' => 'Kabupaten Mandailing Natal'),
      array('id' => '1203','provinsi_id' => '12','nama' => 'Kabupaten Tapanuli Selatan'),
      array('id' => '1204','provinsi_id' => '12','nama' => 'Kabupaten Tapanuli Tengah'),
      array('id' => '1205','provinsi_id' => '12','nama' => 'Kabupaten Tapanuli Utara'),
      array('id' => '1206','provinsi_id' => '12','nama' => 'Kabupaten Toba Samosir'),
      array('id' => '1207','provinsi_id' => '12','nama' => 'Kabupaten Labuhan Batu'),
      array('id' => '1208','provinsi_id' => '12','nama' => 'Kabupaten Asahan'),
      array('id' => '1209','provinsi_id' => '12','nama' => 'Kabupaten Simalungun'),
      array('id' => '1210','provinsi_id' => '12','nama' => 'Kabupaten Dairi'),
      array('id' => '1211','provinsi_id' => '12','nama' => 'Kabupaten Karo'),
      array('id' => '1212','provinsi_id' => '12','nama' => 'Kabupaten Deli Serdang'),
      array('id' => '1213','provinsi_id' => '12','nama' => 'Kabupaten Langkat'),
      array('id' => '1214','provinsi_id' => '12','nama' => 'Kabupaten Nias Selatan'),
      array('id' => '1215','provinsi_id' => '12','nama' => 'Kabupaten Humbang Hasundutan'),
      array('id' => '1216','provinsi_id' => '12','nama' => 'Kabupaten Pakpak Bharat'),
      array('id' => '1217','provinsi_id' => '12','nama' => 'Kabupaten Samosir'),
      array('id' => '1218','provinsi_id' => '12','nama' => 'Kabupaten Serdang Bedagai'),
      array('id' => '1219','provinsi_id' => '12','nama' => 'Kabupaten Batu Bara'),
      array('id' => '1220','provinsi_id' => '12','nama' => 'Kabupaten Padang Lawas Utara'),
      array('id' => '1221','provinsi_id' => '12','nama' => 'Kabupaten Padang Lawas'),
      array('id' => '1222','provinsi_id' => '12','nama' => 'Kabupaten Labuhan Batu Selatan'),
      array('id' => '1223','provinsi_id' => '12','nama' => 'Kabupaten Labuhan Batu Utara'),
      array('id' => '1224','provinsi_id' => '12','nama' => 'Kabupaten Nias Utara'),
      array('id' => '1225','provinsi_id' => '12','nama' => 'Kabupaten Nias Barat'),
      array('id' => '1271','provinsi_id' => '12','nama' => 'Kota Sibolga'),
      array('id' => '1272','provinsi_id' => '12','nama' => 'Kota Tanjung Balai'),
      array('id' => '1273','provinsi_id' => '12','nama' => 'Kota Pematang Siantar'),
      array('id' => '1274','provinsi_id' => '12','nama' => 'Kota Tebing Tinggi'),
      array('id' => '1275','provinsi_id' => '12','nama' => 'Kota Medan'),
      array('id' => '1276','provinsi_id' => '12','nama' => 'Kota Binjai'),
      array('id' => '1277','provinsi_id' => '12','nama' => 'Kota Padangsidimpuan'),
      array('id' => '1278','provinsi_id' => '12','nama' => 'Kota Gunungsitoli'),
      array('id' => '1301','provinsi_id' => '13','nama' => 'Kabupaten Kepulauan Mentawai'),
      array('id' => '1302','provinsi_id' => '13','nama' => 'Kabupaten Pesisir Selatan'),
      array('id' => '1303','provinsi_id' => '13','nama' => 'Kabupaten Solok'),
      array('id' => '1304','provinsi_id' => '13','nama' => 'Kabupaten Sijunjung'),
      array('id' => '1305','provinsi_id' => '13','nama' => 'Kabupaten Tanah Datar'),
      array('id' => '1306','provinsi_id' => '13','nama' => 'Kabupaten Padang Pariaman'),
      array('id' => '1307','provinsi_id' => '13','nama' => 'Kabupaten Agam'),
      array('id' => '1308','provinsi_id' => '13','nama' => 'Kabupaten Lima Puluh Kota'),
      array('id' => '1309','provinsi_id' => '13','nama' => 'Kabupaten Pasaman'),
      array('id' => '1310','provinsi_id' => '13','nama' => 'Kabupaten Solok Selatan'),
      array('id' => '1311','provinsi_id' => '13','nama' => 'Kabupaten Dharmasraya'),
      array('id' => '1312','provinsi_id' => '13','nama' => 'Kabupaten Pasaman Barat'),
      array('id' => '1371','provinsi_id' => '13','nama' => 'Kota Padang'),
      array('id' => '1372','provinsi_id' => '13','nama' => 'Kota Solok'),
      array('id' => '1373','provinsi_id' => '13','nama' => 'Kota Sawah Lunto'),
      array('id' => '1374','provinsi_id' => '13','nama' => 'Kota Padang Panjang'),
      array('id' => '1375','provinsi_id' => '13','nama' => 'Kota Bukittinggi'),
      array('id' => '1376','provinsi_id' => '13','nama' => 'Kota Payakumbuh'),
      array('id' => '1377','provinsi_id' => '13','nama' => 'Kota Pariaman'),
      array('id' => '1401','provinsi_id' => '14','nama' => 'Kabupaten Kuantan Singingi'),
      array('id' => '1402','provinsi_id' => '14','nama' => 'Kabupaten Indragiri Hulu'),
      array('id' => '1403','provinsi_id' => '14','nama' => 'Kabupaten Indragiri Hilir'),
      array('id' => '1404','provinsi_id' => '14','nama' => 'Kabupaten Pelalawan'),
      array('id' => '1405','provinsi_id' => '14','nama' => 'Kabupaten S I A K'),
      array('id' => '1406','provinsi_id' => '14','nama' => 'Kabupaten Kampar'),
      array('id' => '1407','provinsi_id' => '14','nama' => 'Kabupaten Rokan Hulu'),
      array('id' => '1408','provinsi_id' => '14','nama' => 'Kabupaten Bengkalis'),
      array('id' => '1409','provinsi_id' => '14','nama' => 'Kabupaten Rokan Hilir'),
      array('id' => '1410','provinsi_id' => '14','nama' => 'Kabupaten Kepulauan Meranti'),
      array('id' => '1471','provinsi_id' => '14','nama' => 'Kota Pekanbaru'),
      array('id' => '1473','provinsi_id' => '14','nama' => 'Kota D U M A I'),
      array('id' => '1501','provinsi_id' => '15','nama' => 'Kabupaten Kerinci'),
      array('id' => '1502','provinsi_id' => '15','nama' => 'Kabupaten Merangin'),
      array('id' => '1503','provinsi_id' => '15','nama' => 'Kabupaten Sarolangun'),
      array('id' => '1504','provinsi_id' => '15','nama' => 'Kabupaten Batang Hari'),
      array('id' => '1505','provinsi_id' => '15','nama' => 'Kabupaten Muaro Jambi'),
      array('id' => '1506','provinsi_id' => '15','nama' => 'Kabupaten Tanjung Jabung Timur'),
      array('id' => '1507','provinsi_id' => '15','nama' => 'Kabupaten Tanjung Jabung Barat'),
      array('id' => '1508','provinsi_id' => '15','nama' => 'Kabupaten Tebo'),
      array('id' => '1509','provinsi_id' => '15','nama' => 'Kabupaten Bungo'),
      array('id' => '1571','provinsi_id' => '15','nama' => 'Kota Jambi'),
      array('id' => '1572','provinsi_id' => '15','nama' => 'Kota Sungai Penuh'),
      array('id' => '1601','provinsi_id' => '16','nama' => 'Kabupaten Ogan Komering Ulu'),
      array('id' => '1602','provinsi_id' => '16','nama' => 'Kabupaten Ogan Komering Ilir'),
      array('id' => '1603','provinsi_id' => '16','nama' => 'Kabupaten Muara Enim'),
      array('id' => '1604','provinsi_id' => '16','nama' => 'Kabupaten Lahat'),
      array('id' => '1605','provinsi_id' => '16','nama' => 'Kabupaten Musi Rawas'),
      array('id' => '1606','provinsi_id' => '16','nama' => 'Kabupaten Musi Banyuasin'),
      array('id' => '1607','provinsi_id' => '16','nama' => 'Kabupaten Banyu Asin'),
      array('id' => '1608','provinsi_id' => '16','nama' => 'Kabupaten Ogan Komering Ulu Selatan'),
      array('id' => '1609','provinsi_id' => '16','nama' => 'Kabupaten Ogan Komering Ulu Timur'),
      array('id' => '1610','provinsi_id' => '16','nama' => 'Kabupaten Ogan Ilir'),
      array('id' => '1611','provinsi_id' => '16','nama' => 'Kabupaten Empat Lawang'),
      array('id' => '1612','provinsi_id' => '16','nama' => 'Kabupaten Penukal Abab Lematang Ilir'),
      array('id' => '1613','provinsi_id' => '16','nama' => 'Kabupaten Musi Rawas Utara'),
      array('id' => '1671','provinsi_id' => '16','nama' => 'Kota Palembang'),
      array('id' => '1672','provinsi_id' => '16','nama' => 'Kota Prabumulih'),
      array('id' => '1673','provinsi_id' => '16','nama' => 'Kota Pagar Alam'),
      array('id' => '1674','provinsi_id' => '16','nama' => 'Kota Lubuklinggau'),
      array('id' => '1701','provinsi_id' => '17','nama' => 'Kabupaten Bengkulu Selatan'),
      array('id' => '1702','provinsi_id' => '17','nama' => 'Kabupaten Rejang Lebong'),
      array('id' => '1703','provinsi_id' => '17','nama' => 'Kabupaten Bengkulu Utara'),
      array('id' => '1704','provinsi_id' => '17','nama' => 'Kabupaten Kaur'),
      array('id' => '1705','provinsi_id' => '17','nama' => 'Kabupaten Seluma'),
      array('id' => '1706','provinsi_id' => '17','nama' => 'Kabupaten Mukomuko'),
      array('id' => '1707','provinsi_id' => '17','nama' => 'Kabupaten Lebong'),
      array('id' => '1708','provinsi_id' => '17','nama' => 'Kabupaten Kepahiang'),
      array('id' => '1709','provinsi_id' => '17','nama' => 'Kabupaten Bengkulu Tengah'),
      array('id' => '1771','provinsi_id' => '17','nama' => 'Kota Bengkulu'),
      array('id' => '1801','provinsi_id' => '18','nama' => 'Kabupaten Lampung Barat'),
      array('id' => '1802','provinsi_id' => '18','nama' => 'Kabupaten Tanggamus'),
      array('id' => '1803','provinsi_id' => '18','nama' => 'Kabupaten Lampung Selatan'),
      array('id' => '1804','provinsi_id' => '18','nama' => 'Kabupaten Lampung Timur'),
      array('id' => '1805','provinsi_id' => '18','nama' => 'Kabupaten Lampung Tengah'),
      array('id' => '1806','provinsi_id' => '18','nama' => 'Kabupaten Lampung Utara'),
      array('id' => '1807','provinsi_id' => '18','nama' => 'Kabupaten Way Kanan'),
      array('id' => '1808','provinsi_id' => '18','nama' => 'Kabupaten Tulangbawang'),
      array('id' => '1809','provinsi_id' => '18','nama' => 'Kabupaten Pesawaran'),
      array('id' => '1810','provinsi_id' => '18','nama' => 'Kabupaten Pringsewu'),
      array('id' => '1811','provinsi_id' => '18','nama' => 'Kabupaten Mesuji'),
      array('id' => '1812','provinsi_id' => '18','nama' => 'Kabupaten Tulang Bawang Barat'),
      array('id' => '1813','provinsi_id' => '18','nama' => 'Kabupaten Pesisir Barat'),
      array('id' => '1871','provinsi_id' => '18','nama' => 'Kota Bandar Lampung'),
      array('id' => '1872','provinsi_id' => '18','nama' => 'Kota Metro'),
      array('id' => '1901','provinsi_id' => '19','nama' => 'Kabupaten Bangka'),
      array('id' => '1902','provinsi_id' => '19','nama' => 'Kabupaten Belitung'),
      array('id' => '1903','provinsi_id' => '19','nama' => 'Kabupaten Bangka Barat'),
      array('id' => '1904','provinsi_id' => '19','nama' => 'Kabupaten Bangka Tengah'),
      array('id' => '1905','provinsi_id' => '19','nama' => 'Kabupaten Bangka Selatan'),
      array('id' => '1906','provinsi_id' => '19','nama' => 'Kabupaten Belitung Timur'),
      array('id' => '1971','provinsi_id' => '19','nama' => 'Kota Pangkal Pinang'),
      array('id' => '2101','provinsi_id' => '21','nama' => 'Kabupaten Karimun'),
      array('id' => '2102','provinsi_id' => '21','nama' => 'Kabupaten Bintan'),
      array('id' => '2103','provinsi_id' => '21','nama' => 'Kabupaten Natuna'),
      array('id' => '2104','provinsi_id' => '21','nama' => 'Kabupaten Lingga'),
      array('id' => '2105','provinsi_id' => '21','nama' => 'Kabupaten Kepulauan Anambas'),
      array('id' => '2171','provinsi_id' => '21','nama' => 'Kota B A T A M'),
      array('id' => '2172','provinsi_id' => '21','nama' => 'Kota Tanjung Pinang'),
      array('id' => '3101','provinsi_id' => '31','nama' => 'Kabupaten Kepulauan Seribu'),
      array('id' => '3171','provinsi_id' => '31','nama' => 'Kota Jakarta Selatan'),
      array('id' => '3172','provinsi_id' => '31','nama' => 'Kota Jakarta Timur'),
      array('id' => '3173','provinsi_id' => '31','nama' => 'Kota Jakarta Pusat'),
      array('id' => '3174','provinsi_id' => '31','nama' => 'Kota Jakarta Barat'),
      array('id' => '3175','provinsi_id' => '31','nama' => 'Kota Jakarta Utara'),
      array('id' => '3201','provinsi_id' => '32','nama' => 'Kabupaten Bogor'),
      array('id' => '3202','provinsi_id' => '32','nama' => 'Kabupaten Sukabumi'),
      array('id' => '3203','provinsi_id' => '32','nama' => 'Kabupaten Cianjur'),
      array('id' => '3204','provinsi_id' => '32','nama' => 'Kabupaten Bandung'),
      array('id' => '3205','provinsi_id' => '32','nama' => 'Kabupaten Garut'),
      array('id' => '3206','provinsi_id' => '32','nama' => 'Kabupaten Tasikmalaya'),
      array('id' => '3207','provinsi_id' => '32','nama' => 'Kabupaten Ciamis'),
      array('id' => '3208','provinsi_id' => '32','nama' => 'Kabupaten Kuningan'),
      array('id' => '3209','provinsi_id' => '32','nama' => 'Kabupaten Cirebon'),
      array('id' => '3210','provinsi_id' => '32','nama' => 'Kabupaten Majalengka'),
      array('id' => '3211','provinsi_id' => '32','nama' => 'Kabupaten Sumedang'),
      array('id' => '3212','provinsi_id' => '32','nama' => 'Kabupaten Indramayu'),
      array('id' => '3213','provinsi_id' => '32','nama' => 'Kabupaten Subang'),
      array('id' => '3214','provinsi_id' => '32','nama' => 'Kabupaten Purwakarta'),
      array('id' => '3215','provinsi_id' => '32','nama' => 'Kabupaten Karawang'),
      array('id' => '3216','provinsi_id' => '32','nama' => 'Kabupaten Bekasi'),
      array('id' => '3217','provinsi_id' => '32','nama' => 'Kabupaten Bandung Barat'),
      array('id' => '3218','provinsi_id' => '32','nama' => 'Kabupaten Pangandaran'),
      array('id' => '3271','provinsi_id' => '32','nama' => 'Kota Bogor'),
      array('id' => '3272','provinsi_id' => '32','nama' => 'Kota Sukabumi'),
      array('id' => '3273','provinsi_id' => '32','nama' => 'Kota Bandung'),
      array('id' => '3274','provinsi_id' => '32','nama' => 'Kota Cirebon'),
      array('id' => '3275','provinsi_id' => '32','nama' => 'Kota Bekasi'),
      array('id' => '3276','provinsi_id' => '32','nama' => 'Kota Depok'),
      array('id' => '3277','provinsi_id' => '32','nama' => 'Kota Cimahi'),
      array('id' => '3278','provinsi_id' => '32','nama' => 'Kota Tasikmalaya'),
      array('id' => '3279','provinsi_id' => '32','nama' => 'Kota Banjar'),
      array('id' => '3301','provinsi_id' => '33','nama' => 'Kabupaten Cilacap'),
      array('id' => '3302','provinsi_id' => '33','nama' => 'Kabupaten Banyumas'),
      array('id' => '3303','provinsi_id' => '33','nama' => 'Kabupaten Purbalingga'),
      array('id' => '3304','provinsi_id' => '33','nama' => 'Kabupaten Banjarnegara'),
      array('id' => '3305','provinsi_id' => '33','nama' => 'Kabupaten Kebumen'),
      array('id' => '3306','provinsi_id' => '33','nama' => 'Kabupaten Purworejo'),
      array('id' => '3307','provinsi_id' => '33','nama' => 'Kabupaten Wonosobo'),
      array('id' => '3308','provinsi_id' => '33','nama' => 'Kabupaten Magelang'),
      array('id' => '3309','provinsi_id' => '33','nama' => 'Kabupaten Boyolali'),
      array('id' => '3310','provinsi_id' => '33','nama' => 'Kabupaten Klaten'),
      array('id' => '3311','provinsi_id' => '33','nama' => 'Kabupaten Sukoharjo'),
      array('id' => '3312','provinsi_id' => '33','nama' => 'Kabupaten Wonogiri'),
      array('id' => '3313','provinsi_id' => '33','nama' => 'Kabupaten Karanganyar'),
      array('id' => '3314','provinsi_id' => '33','nama' => 'Kabupaten Sragen'),
      array('id' => '3315','provinsi_id' => '33','nama' => 'Kabupaten Grobogan'),
      array('id' => '3316','provinsi_id' => '33','nama' => 'Kabupaten Blora'),
      array('id' => '3317','provinsi_id' => '33','nama' => 'Kabupaten Rembang'),
      array('id' => '3318','provinsi_id' => '33','nama' => 'Kabupaten Pati'),
      array('id' => '3319','provinsi_id' => '33','nama' => 'Kabupaten Kudus'),
      array('id' => '3320','provinsi_id' => '33','nama' => 'Kabupaten Jepara'),
      array('id' => '3321','provinsi_id' => '33','nama' => 'Kabupaten Demak'),
      array('id' => '3322','provinsi_id' => '33','nama' => 'Kabupaten Semarang'),
      array('id' => '3323','provinsi_id' => '33','nama' => 'Kabupaten Temanggung'),
      array('id' => '3324','provinsi_id' => '33','nama' => 'Kabupaten Kendal'),
      array('id' => '3325','provinsi_id' => '33','nama' => 'Kabupaten Batang'),
      array('id' => '3326','provinsi_id' => '33','nama' => 'Kabupaten Pekalongan'),
      array('id' => '3327','provinsi_id' => '33','nama' => 'Kabupaten Pemalang'),
      array('id' => '3328','provinsi_id' => '33','nama' => 'Kabupaten Tegal'),
      array('id' => '3329','provinsi_id' => '33','nama' => 'Kabupaten Brebes'),
      array('id' => '3371','provinsi_id' => '33','nama' => 'Kota Magelang'),
      array('id' => '3372','provinsi_id' => '33','nama' => 'Kota Surakarta'),
      array('id' => '3373','provinsi_id' => '33','nama' => 'Kota Salatiga'),
      array('id' => '3374','provinsi_id' => '33','nama' => 'Kota Semarang'),
      array('id' => '3375','provinsi_id' => '33','nama' => 'Kota Pekalongan'),
      array('id' => '3376','provinsi_id' => '33','nama' => 'Kota Tegal'),
      array('id' => '3401','provinsi_id' => '34','nama' => 'Kabupaten Kulon Progo'),
      array('id' => '3402','provinsi_id' => '34','nama' => 'Kabupaten Bantul'),
      array('id' => '3403','provinsi_id' => '34','nama' => 'Kabupaten Gunung Kidul'),
      array('id' => '3404','provinsi_id' => '34','nama' => 'Kabupaten Sleman'),
      array('id' => '3471','provinsi_id' => '34','nama' => 'Kota Yogyakarta'),
      array('id' => '3501','provinsi_id' => '35','nama' => 'Kabupaten Pacitan'),
      array('id' => '3502','provinsi_id' => '35','nama' => 'Kabupaten Ponorogo'),
      array('id' => '3503','provinsi_id' => '35','nama' => 'Kabupaten Trenggalek'),
      array('id' => '3504','provinsi_id' => '35','nama' => 'Kabupaten Tulungagung'),
      array('id' => '3505','provinsi_id' => '35','nama' => 'Kabupaten Blitar'),
      array('id' => '3506','provinsi_id' => '35','nama' => 'Kabupaten Kediri'),
      array('id' => '3507','provinsi_id' => '35','nama' => 'Kabupaten Malang'),
      array('id' => '3508','provinsi_id' => '35','nama' => 'Kabupaten Lumajang'),
      array('id' => '3509','provinsi_id' => '35','nama' => 'Kabupaten Jember'),
      array('id' => '3510','provinsi_id' => '35','nama' => 'Kabupaten Banyuwangi'),
      array('id' => '3511','provinsi_id' => '35','nama' => 'Kabupaten Bondowoso'),
      array('id' => '3512','provinsi_id' => '35','nama' => 'Kabupaten Situbondo'),
      array('id' => '3513','provinsi_id' => '35','nama' => 'Kabupaten Probolinggo'),
      array('id' => '3514','provinsi_id' => '35','nama' => 'Kabupaten Pasuruan'),
      array('id' => '3515','provinsi_id' => '35','nama' => 'Kabupaten Sidoarjo'),
      array('id' => '3516','provinsi_id' => '35','nama' => 'Kabupaten Mojokerto'),
      array('id' => '3517','provinsi_id' => '35','nama' => 'Kabupaten Jombang'),
      array('id' => '3518','provinsi_id' => '35','nama' => 'Kabupaten Nganjuk'),
      array('id' => '3519','provinsi_id' => '35','nama' => 'Kabupaten Madiun'),
      array('id' => '3520','provinsi_id' => '35','nama' => 'Kabupaten Magetan'),
      array('id' => '3521','provinsi_id' => '35','nama' => 'Kabupaten Ngawi'),
      array('id' => '3522','provinsi_id' => '35','nama' => 'Kabupaten Bojonegoro'),
      array('id' => '3523','provinsi_id' => '35','nama' => 'Kabupaten Tuban'),
      array('id' => '3524','provinsi_id' => '35','nama' => 'Kabupaten Lamongan'),
      array('id' => '3525','provinsi_id' => '35','nama' => 'Kabupaten Gresik'),
      array('id' => '3526','provinsi_id' => '35','nama' => 'Kabupaten Bangkalan'),
      array('id' => '3527','provinsi_id' => '35','nama' => 'Kabupaten Sampang'),
      array('id' => '3528','provinsi_id' => '35','nama' => 'Kabupaten Pamekasan'),
      array('id' => '3529','provinsi_id' => '35','nama' => 'Kabupaten Sumenep'),
      array('id' => '3571','provinsi_id' => '35','nama' => 'Kota Kediri'),
      array('id' => '3572','provinsi_id' => '35','nama' => 'Kota Blitar'),
      array('id' => '3573','provinsi_id' => '35','nama' => 'Kota Malang'),
      array('id' => '3574','provinsi_id' => '35','nama' => 'Kota Probolinggo'),
      array('id' => '3575','provinsi_id' => '35','nama' => 'Kota Pasuruan'),
      array('id' => '3576','provinsi_id' => '35','nama' => 'Kota Mojokerto'),
      array('id' => '3577','provinsi_id' => '35','nama' => 'Kota Madiun'),
      array('id' => '3578','provinsi_id' => '35','nama' => 'Kota Surabaya'),
      array('id' => '3579','provinsi_id' => '35','nama' => 'Kota Batu'),
      array('id' => '3601','provinsi_id' => '36','nama' => 'Kabupaten Pandeglang'),
      array('id' => '3602','provinsi_id' => '36','nama' => 'Kabupaten Lebak'),
      array('id' => '3603','provinsi_id' => '36','nama' => 'Kabupaten Tangerang'),
      array('id' => '3604','provinsi_id' => '36','nama' => 'Kabupaten Serang'),
      array('id' => '3671','provinsi_id' => '36','nama' => 'Kota Tangerang'),
      array('id' => '3672','provinsi_id' => '36','nama' => 'Kota Cilegon'),
      array('id' => '3673','provinsi_id' => '36','nama' => 'Kota Serang'),
      array('id' => '3674','provinsi_id' => '36','nama' => 'Kota Tangerang Selatan'),
      array('id' => '5101','provinsi_id' => '51','nama' => 'Kabupaten Jembrana'),
      array('id' => '5102','provinsi_id' => '51','nama' => 'Kabupaten Tabanan'),
      array('id' => '5103','provinsi_id' => '51','nama' => 'Kabupaten Badung'),
      array('id' => '5104','provinsi_id' => '51','nama' => 'Kabupaten Gianyar'),
      array('id' => '5105','provinsi_id' => '51','nama' => 'Kabupaten Klungkung'),
      array('id' => '5106','provinsi_id' => '51','nama' => 'Kabupaten Bangli'),
      array('id' => '5107','provinsi_id' => '51','nama' => 'Kabupaten Karang Asem'),
      array('id' => '5108','provinsi_id' => '51','nama' => 'Kabupaten Buleleng'),
      array('id' => '5171','provinsi_id' => '51','nama' => 'Kota Denpasar'),
      array('id' => '5201','provinsi_id' => '52','nama' => 'Kabupaten Lombok Barat'),
      array('id' => '5202','provinsi_id' => '52','nama' => 'Kabupaten Lombok Tengah'),
      array('id' => '5203','provinsi_id' => '52','nama' => 'Kabupaten Lombok Timur'),
      array('id' => '5204','provinsi_id' => '52','nama' => 'Kabupaten Sumbawa'),
      array('id' => '5205','provinsi_id' => '52','nama' => 'Kabupaten Dompu'),
      array('id' => '5206','provinsi_id' => '52','nama' => 'Kabupaten Bima'),
      array('id' => '5207','provinsi_id' => '52','nama' => 'Kabupaten Sumbawa Barat'),
      array('id' => '5208','provinsi_id' => '52','nama' => 'Kabupaten Lombok Utara'),
      array('id' => '5271','provinsi_id' => '52','nama' => 'Kota Mataram'),
      array('id' => '5272','provinsi_id' => '52','nama' => 'Kota Bima'),
      array('id' => '5301','provinsi_id' => '53','nama' => 'Kabupaten Sumba Barat'),
      array('id' => '5302','provinsi_id' => '53','nama' => 'Kabupaten Sumba Timur'),
      array('id' => '5303','provinsi_id' => '53','nama' => 'Kabupaten Kupang'),
      array('id' => '5304','provinsi_id' => '53','nama' => 'Kabupaten Timor Tengah Selatan'),
      array('id' => '5305','provinsi_id' => '53','nama' => 'Kabupaten Timor Tengah Utara'),
      array('id' => '5306','provinsi_id' => '53','nama' => 'Kabupaten Belu'),
      array('id' => '5307','provinsi_id' => '53','nama' => 'Kabupaten Alor'),
      array('id' => '5308','provinsi_id' => '53','nama' => 'Kabupaten Lembata'),
      array('id' => '5309','provinsi_id' => '53','nama' => 'Kabupaten Flores Timur'),
      array('id' => '5310','provinsi_id' => '53','nama' => 'Kabupaten Sikka'),
      array('id' => '5311','provinsi_id' => '53','nama' => 'Kabupaten Ende'),
      array('id' => '5312','provinsi_id' => '53','nama' => 'Kabupaten Ngada'),
      array('id' => '5313','provinsi_id' => '53','nama' => 'Kabupaten Manggarai'),
      array('id' => '5314','provinsi_id' => '53','nama' => 'Kabupaten Rote Ndao'),
      array('id' => '5315','provinsi_id' => '53','nama' => 'Kabupaten Manggarai Barat'),
      array('id' => '5316','provinsi_id' => '53','nama' => 'Kabupaten Sumba Tengah'),
      array('id' => '5317','provinsi_id' => '53','nama' => 'Kabupaten Sumba Barat Daya'),
      array('id' => '5318','provinsi_id' => '53','nama' => 'Kabupaten Nagekeo'),
      array('id' => '5319','provinsi_id' => '53','nama' => 'Kabupaten Manggarai Timur'),
      array('id' => '5320','provinsi_id' => '53','nama' => 'Kabupaten Sabu Raijua'),
      array('id' => '5321','provinsi_id' => '53','nama' => 'Kabupaten Malaka'),
      array('id' => '5371','provinsi_id' => '53','nama' => 'Kota Kupang'),
      array('id' => '6101','provinsi_id' => '61','nama' => 'Kabupaten Sambas'),
      array('id' => '6102','provinsi_id' => '61','nama' => 'Kabupaten Bengkayang'),
      array('id' => '6103','provinsi_id' => '61','nama' => 'Kabupaten Landak'),
      array('id' => '6104','provinsi_id' => '61','nama' => 'Kabupaten Mempawah'),
      array('id' => '6105','provinsi_id' => '61','nama' => 'Kabupaten Sanggau'),
      array('id' => '6106','provinsi_id' => '61','nama' => 'Kabupaten Ketapang'),
      array('id' => '6107','provinsi_id' => '61','nama' => 'Kabupaten Sintang'),
      array('id' => '6108','provinsi_id' => '61','nama' => 'Kabupaten Kapuas Hulu'),
      array('id' => '6109','provinsi_id' => '61','nama' => 'Kabupaten Sekadau'),
      array('id' => '6110','provinsi_id' => '61','nama' => 'Kabupaten Melawi'),
      array('id' => '6111','provinsi_id' => '61','nama' => 'Kabupaten Kayong Utara'),
      array('id' => '6112','provinsi_id' => '61','nama' => 'Kabupaten Kubu Raya'),
      array('id' => '6171','provinsi_id' => '61','nama' => 'Kota Pontianak'),
      array('id' => '6172','provinsi_id' => '61','nama' => 'Kota Singkawang'),
      array('id' => '6201','provinsi_id' => '62','nama' => 'Kabupaten Kotawaringin Barat'),
      array('id' => '6202','provinsi_id' => '62','nama' => 'Kabupaten Kotawaringin Timur'),
      array('id' => '6203','provinsi_id' => '62','nama' => 'Kabupaten Kapuas'),
      array('id' => '6204','provinsi_id' => '62','nama' => 'Kabupaten Barito Selatan'),
      array('id' => '6205','provinsi_id' => '62','nama' => 'Kabupaten Barito Utara'),
      array('id' => '6206','provinsi_id' => '62','nama' => 'Kabupaten Sukamara'),
      array('id' => '6207','provinsi_id' => '62','nama' => 'Kabupaten Lamandau'),
      array('id' => '6208','provinsi_id' => '62','nama' => 'Kabupaten Seruyan'),
      array('id' => '6209','provinsi_id' => '62','nama' => 'Kabupaten Katingan'),
      array('id' => '6210','provinsi_id' => '62','nama' => 'Kabupaten Pulang Pisau'),
      array('id' => '6211','provinsi_id' => '62','nama' => 'Kabupaten Gunung Mas'),
      array('id' => '6212','provinsi_id' => '62','nama' => 'Kabupaten Barito Timur'),
      array('id' => '6213','provinsi_id' => '62','nama' => 'Kabupaten Murung Raya'),
      array('id' => '6271','provinsi_id' => '62','nama' => 'Kota Palangka Raya'),
      array('id' => '6301','provinsi_id' => '63','nama' => 'Kabupaten Tanah Laut'),
      array('id' => '6302','provinsi_id' => '63','nama' => 'Kabupaten Kota Baru'),
      array('id' => '6303','provinsi_id' => '63','nama' => 'Kabupaten Banjar'),
      array('id' => '6304','provinsi_id' => '63','nama' => 'Kabupaten Barito Kuala'),
      array('id' => '6305','provinsi_id' => '63','nama' => 'Kabupaten Tapin'),
      array('id' => '6306','provinsi_id' => '63','nama' => 'Kabupaten Hulu Sungai Selatan'),
      array('id' => '6307','provinsi_id' => '63','nama' => 'Kabupaten Hulu Sungai Tengah'),
      array('id' => '6308','provinsi_id' => '63','nama' => 'Kabupaten Hulu Sungai Utara'),
      array('id' => '6309','provinsi_id' => '63','nama' => 'Kabupaten Tabalong'),
      array('id' => '6310','provinsi_id' => '63','nama' => 'Kabupaten Tanah Bumbu'),
      array('id' => '6311','provinsi_id' => '63','nama' => 'Kabupaten Balangan'),
      array('id' => '6371','provinsi_id' => '63','nama' => 'Kota Banjarmasin'),
      array('id' => '6372','provinsi_id' => '63','nama' => 'Kota Banjar Baru'),
      array('id' => '6401','provinsi_id' => '64','nama' => 'Kabupaten Paser'),
      array('id' => '6402','provinsi_id' => '64','nama' => 'Kabupaten Kutai Barat'),
      array('id' => '6403','provinsi_id' => '64','nama' => 'Kabupaten Kutai Kartanegara'),
      array('id' => '6404','provinsi_id' => '64','nama' => 'Kabupaten Kutai Timur'),
      array('id' => '6405','provinsi_id' => '64','nama' => 'Kabupaten Berau'),
      array('id' => '6409','provinsi_id' => '64','nama' => 'Kabupaten Penajam Paser Utara'),
      array('id' => '6411','provinsi_id' => '64','nama' => 'Kabupaten Mahakam Hulu'),
      array('id' => '6471','provinsi_id' => '64','nama' => 'Kota Balikpapan'),
      array('id' => '6472','provinsi_id' => '64','nama' => 'Kota Samarinda'),
      array('id' => '6474','provinsi_id' => '64','nama' => 'Kota Bontang'),
      array('id' => '6501','provinsi_id' => '65','nama' => 'Kabupaten Malinau'),
      array('id' => '6502','provinsi_id' => '65','nama' => 'Kabupaten Bulungan'),
      array('id' => '6503','provinsi_id' => '65','nama' => 'Kabupaten Tana Tidung'),
      array('id' => '6504','provinsi_id' => '65','nama' => 'Kabupaten Nunukan'),
      array('id' => '6571','provinsi_id' => '65','nama' => 'Kota Tarakan'),
      array('id' => '7101','provinsi_id' => '71','nama' => 'Kabupaten Bolaang Mongondow'),
      array('id' => '7102','provinsi_id' => '71','nama' => 'Kabupaten Minahasa'),
      array('id' => '7103','provinsi_id' => '71','nama' => 'Kabupaten Kepulauan Sangihe'),
      array('id' => '7104','provinsi_id' => '71','nama' => 'Kabupaten Kepulauan Talaud'),
      array('id' => '7105','provinsi_id' => '71','nama' => 'Kabupaten Minahasa Selatan'),
      array('id' => '7106','provinsi_id' => '71','nama' => 'Kabupaten Minahasa Utara'),
      array('id' => '7107','provinsi_id' => '71','nama' => 'Kabupaten Bolaang Mongondow Utara'),
      array('id' => '7108','provinsi_id' => '71','nama' => 'Kabupaten Siau Tagulandang Biaro'),
      array('id' => '7109','provinsi_id' => '71','nama' => 'Kabupaten Minahasa Tenggara'),
      array('id' => '7110','provinsi_id' => '71','nama' => 'Kabupaten Bolaang Mongondow Selatan'),
      array('id' => '7111','provinsi_id' => '71','nama' => 'Kabupaten Bolaang Mongondow Timur'),
      array('id' => '7171','provinsi_id' => '71','nama' => 'Kota Manado'),
      array('id' => '7172','provinsi_id' => '71','nama' => 'Kota Bitung'),
      array('id' => '7173','provinsi_id' => '71','nama' => 'Kota Tomohon'),
      array('id' => '7174','provinsi_id' => '71','nama' => 'Kota Kotamobagu'),
      array('id' => '7201','provinsi_id' => '72','nama' => 'Kabupaten Banggai Kepulauan'),
      array('id' => '7202','provinsi_id' => '72','nama' => 'Kabupaten Banggai'),
      array('id' => '7203','provinsi_id' => '72','nama' => 'Kabupaten Morowali'),
      array('id' => '7204','provinsi_id' => '72','nama' => 'Kabupaten Poso'),
      array('id' => '7205','provinsi_id' => '72','nama' => 'Kabupaten Donggala'),
      array('id' => '7206','provinsi_id' => '72','nama' => 'Kabupaten Toli-toli'),
      array('id' => '7207','provinsi_id' => '72','nama' => 'Kabupaten Buol'),
      array('id' => '7208','provinsi_id' => '72','nama' => 'Kabupaten Parigi Moutong'),
      array('id' => '7209','provinsi_id' => '72','nama' => 'Kabupaten Tojo Una-una'),
      array('id' => '7210','provinsi_id' => '72','nama' => 'Kabupaten Sigi'),
      array('id' => '7211','provinsi_id' => '72','nama' => 'Kabupaten Banggai Laut'),
      array('id' => '7212','provinsi_id' => '72','nama' => 'Kabupaten Morowali Utara'),
      array('id' => '7271','provinsi_id' => '72','nama' => 'Kota Palu'),
      array('id' => '7301','provinsi_id' => '73','nama' => 'Kabupaten Kepulauan Selayar'),
      array('id' => '7302','provinsi_id' => '73','nama' => 'Kabupaten Bulukumba'),
      array('id' => '7303','provinsi_id' => '73','nama' => 'Kabupaten Bantaeng'),
      array('id' => '7304','provinsi_id' => '73','nama' => 'Kabupaten Jeneponto'),
      array('id' => '7305','provinsi_id' => '73','nama' => 'Kabupaten Takalar'),
      array('id' => '7306','provinsi_id' => '73','nama' => 'Kabupaten Gowa'),
      array('id' => '7307','provinsi_id' => '73','nama' => 'Kabupaten Sinjai'),
      array('id' => '7308','provinsi_id' => '73','nama' => 'Kabupaten Maros'),
      array('id' => '7309','provinsi_id' => '73','nama' => 'Kabupaten Pangkajene Dan Kepulauan'),
      array('id' => '7310','provinsi_id' => '73','nama' => 'Kabupaten Barru'),
      array('id' => '7311','provinsi_id' => '73','nama' => 'Kabupaten Bone'),
      array('id' => '7312','provinsi_id' => '73','nama' => 'Kabupaten Soppeng'),
      array('id' => '7313','provinsi_id' => '73','nama' => 'Kabupaten Wajo'),
      array('id' => '7314','provinsi_id' => '73','nama' => 'Kabupaten Sidenreng Rappang'),
      array('id' => '7315','provinsi_id' => '73','nama' => 'Kabupaten Pinrang'),
      array('id' => '7316','provinsi_id' => '73','nama' => 'Kabupaten Enrekang'),
      array('id' => '7317','provinsi_id' => '73','nama' => 'Kabupaten Luwu'),
      array('id' => '7318','provinsi_id' => '73','nama' => 'Kabupaten Tana Toraja'),
      array('id' => '7322','provinsi_id' => '73','nama' => 'Kabupaten Luwu Utara'),
      array('id' => '7325','provinsi_id' => '73','nama' => 'Kabupaten Luwu Timur'),
      array('id' => '7326','provinsi_id' => '73','nama' => 'Kabupaten Toraja Utara'),
      array('id' => '7371','provinsi_id' => '73','nama' => 'Kota Makassar'),
      array('id' => '7372','provinsi_id' => '73','nama' => 'Kota Parepare'),
      array('id' => '7373','provinsi_id' => '73','nama' => 'Kota Palopo'),
      array('id' => '7401','provinsi_id' => '74','nama' => 'Kabupaten Buton'),
      array('id' => '7402','provinsi_id' => '74','nama' => 'Kabupaten Muna'),
      array('id' => '7403','provinsi_id' => '74','nama' => 'Kabupaten Konawe'),
      array('id' => '7404','provinsi_id' => '74','nama' => 'Kabupaten Kolaka'),
      array('id' => '7405','provinsi_id' => '74','nama' => 'Kabupaten Konawe Selatan'),
      array('id' => '7406','provinsi_id' => '74','nama' => 'Kabupaten Bombana'),
      array('id' => '7407','provinsi_id' => '74','nama' => 'Kabupaten Wakatobi'),
      array('id' => '7408','provinsi_id' => '74','nama' => 'Kabupaten Kolaka Utara'),
      array('id' => '7409','provinsi_id' => '74','nama' => 'Kabupaten Buton Utara'),
      array('id' => '7410','provinsi_id' => '74','nama' => 'Kabupaten Konawe Utara'),
      array('id' => '7411','provinsi_id' => '74','nama' => 'Kabupaten Kolaka Timur'),
      array('id' => '7412','provinsi_id' => '74','nama' => 'Kabupaten Konawe Kepulauan'),
      array('id' => '7413','provinsi_id' => '74','nama' => 'Kabupaten Muna Barat'),
      array('id' => '7414','provinsi_id' => '74','nama' => 'Kabupaten Buton Tengah'),
      array('id' => '7415','provinsi_id' => '74','nama' => 'Kabupaten Buton Selatan'),
      array('id' => '7471','provinsi_id' => '74','nama' => 'Kota Kendari'),
      array('id' => '7472','provinsi_id' => '74','nama' => 'Kota Baubau'),
      array('id' => '7501','provinsi_id' => '75','nama' => 'Kabupaten Boalemo'),
      array('id' => '7502','provinsi_id' => '75','nama' => 'Kabupaten Gorontalo'),
      array('id' => '7503','provinsi_id' => '75','nama' => 'Kabupaten Pohuwato'),
      array('id' => '7504','provinsi_id' => '75','nama' => 'Kabupaten Bone Bolango'),
      array('id' => '7505','provinsi_id' => '75','nama' => 'Kabupaten Gorontalo Utara'),
      array('id' => '7571','provinsi_id' => '75','nama' => 'Kota Gorontalo'),
      array('id' => '7601','provinsi_id' => '76','nama' => 'Kabupaten Majene'),
      array('id' => '7602','provinsi_id' => '76','nama' => 'Kabupaten Polewali Mandar'),
      array('id' => '7603','provinsi_id' => '76','nama' => 'Kabupaten Mamasa'),
      array('id' => '7604','provinsi_id' => '76','nama' => 'Kabupaten Mamuju'),
      array('id' => '7605','provinsi_id' => '76','nama' => 'Kabupaten Mamuju Utara'),
      array('id' => '7606','provinsi_id' => '76','nama' => 'Kabupaten Mamuju Tengah'),
      array('id' => '8101','provinsi_id' => '81','nama' => 'Kabupaten Maluku Tenggara Barat'),
      array('id' => '8102','provinsi_id' => '81','nama' => 'Kabupaten Maluku Tenggara'),
      array('id' => '8103','provinsi_id' => '81','nama' => 'Kabupaten Maluku Tengah'),
      array('id' => '8104','provinsi_id' => '81','nama' => 'Kabupaten Buru'),
      array('id' => '8105','provinsi_id' => '81','nama' => 'Kabupaten Kepulauan Aru'),
      array('id' => '8106','provinsi_id' => '81','nama' => 'Kabupaten Seram Bagian Barat'),
      array('id' => '8107','provinsi_id' => '81','nama' => 'Kabupaten Seram Bagian Timur'),
      array('id' => '8108','provinsi_id' => '81','nama' => 'Kabupaten Maluku Barat Daya'),
      array('id' => '8109','provinsi_id' => '81','nama' => 'Kabupaten Buru Selatan'),
      array('id' => '8171','provinsi_id' => '81','nama' => 'Kota Ambon'),
      array('id' => '8172','provinsi_id' => '81','nama' => 'Kota Tual'),
      array('id' => '8201','provinsi_id' => '82','nama' => 'Kabupaten Halmahera Barat'),
      array('id' => '8202','provinsi_id' => '82','nama' => 'Kabupaten Halmahera Tengah'),
      array('id' => '8203','provinsi_id' => '82','nama' => 'Kabupaten Kepulauan Sula'),
      array('id' => '8204','provinsi_id' => '82','nama' => 'Kabupaten Halmahera Selatan'),
      array('id' => '8205','provinsi_id' => '82','nama' => 'Kabupaten Halmahera Utara'),
      array('id' => '8206','provinsi_id' => '82','nama' => 'Kabupaten Halmahera Timur'),
      array('id' => '8207','provinsi_id' => '82','nama' => 'Kabupaten Pulau Morotai'),
      array('id' => '8208','provinsi_id' => '82','nama' => 'Kabupaten Pulau Taliabu'),
      array('id' => '8271','provinsi_id' => '82','nama' => 'Kota Ternate'),
      array('id' => '8272','provinsi_id' => '82','nama' => 'Kota Tidore Kepulauan'),
      array('id' => '9101','provinsi_id' => '91','nama' => 'Kabupaten Fakfak'),
      array('id' => '9102','provinsi_id' => '91','nama' => 'Kabupaten Kaimana'),
      array('id' => '9103','provinsi_id' => '91','nama' => 'Kabupaten Teluk Wondama'),
      array('id' => '9104','provinsi_id' => '91','nama' => 'Kabupaten Teluk Bintuni'),
      array('id' => '9105','provinsi_id' => '91','nama' => 'Kabupaten Manokwari'),
      array('id' => '9106','provinsi_id' => '91','nama' => 'Kabupaten Sorong Selatan'),
      array('id' => '9107','provinsi_id' => '91','nama' => 'Kabupaten Sorong'),
      array('id' => '9108','provinsi_id' => '91','nama' => 'Kabupaten Raja Ampat'),
      array('id' => '9109','provinsi_id' => '91','nama' => 'Kabupaten Tambrauw'),
      array('id' => '9110','provinsi_id' => '91','nama' => 'Kabupaten Maybrat'),
      array('id' => '9111','provinsi_id' => '91','nama' => 'Kabupaten Manokwari Selatan'),
      array('id' => '9112','provinsi_id' => '91','nama' => 'Kabupaten Pegunungan Arfak'),
      array('id' => '9171','provinsi_id' => '91','nama' => 'Kota Sorong'),
      array('id' => '9401','provinsi_id' => '94','nama' => 'Kabupaten Merauke'),
      array('id' => '9402','provinsi_id' => '94','nama' => 'Kabupaten Jayawijaya'),
      array('id' => '9403','provinsi_id' => '94','nama' => 'Kabupaten Jayapura'),
      array('id' => '9404','provinsi_id' => '94','nama' => 'Kabupaten Nabire'),
      array('id' => '9408','provinsi_id' => '94','nama' => 'Kabupaten Kepulauan Yapen'),
      array('id' => '9409','provinsi_id' => '94','nama' => 'Kabupaten Biak Numfor'),
      array('id' => '9410','provinsi_id' => '94','nama' => 'Kabupaten Paniai'),
      array('id' => '9411','provinsi_id' => '94','nama' => 'Kabupaten Puncak Jaya'),
      array('id' => '9412','provinsi_id' => '94','nama' => 'Kabupaten Mimika'),
      array('id' => '9413','provinsi_id' => '94','nama' => 'Kabupaten Boven Digoel'),
      array('id' => '9414','provinsi_id' => '94','nama' => 'Kabupaten Mappi'),
      array('id' => '9415','provinsi_id' => '94','nama' => 'Kabupaten Asmat'),
      array('id' => '9416','provinsi_id' => '94','nama' => 'Kabupaten Yahukimo'),
      array('id' => '9417','provinsi_id' => '94','nama' => 'Kabupaten Pegunungan Bintang'),
      array('id' => '9418','provinsi_id' => '94','nama' => 'Kabupaten Tolikara'),
      array('id' => '9419','provinsi_id' => '94','nama' => 'Kabupaten Sarmi'),
      array('id' => '9420','provinsi_id' => '94','nama' => 'Kabupaten Keerom'),
      array('id' => '9426','provinsi_id' => '94','nama' => 'Kabupaten Waropen'),
      array('id' => '9427','provinsi_id' => '94','nama' => 'Kabupaten Supiori'),
      array('id' => '9428','provinsi_id' => '94','nama' => 'Kabupaten Mamberamo Raya'),
      array('id' => '9429','provinsi_id' => '94','nama' => 'Kabupaten Nduga'),
      array('id' => '9430','provinsi_id' => '94','nama' => 'Kabupaten Lanny Jaya'),
      array('id' => '9431','provinsi_id' => '94','nama' => 'Kabupaten Mamberamo Tengah'),
      array('id' => '9432','provinsi_id' => '94','nama' => 'Kabupaten Yalimo'),
      array('id' => '9433','provinsi_id' => '94','nama' => 'Kabupaten Puncak'),
      array('id' => '9434','provinsi_id' => '94','nama' => 'Kabupaten Dogiyai'),
      array('id' => '9435','provinsi_id' => '94','nama' => 'Kabupaten Intan Jaya'),
      array('id' => '9436','provinsi_id' => '94','nama' => 'Kabupaten Deiyai'),
      array('id' => '9471','provinsi_id' => '94','nama' => 'Kota JayapurA')
    ];

    if (!DB::table('kotas')->count()) {
      DB::table('kotas')->insert($Kota);
    }
  }
}
